services:
  - type: web
    name: wakfu-hdv-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: SkySynn/SkySynn.github.io
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_DATA_PATH
        value: data/prices.json
      - key: GITHUB_CRAFTS_PATH
        value: data/crafts.json
      - key: JWT_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: admin
